"""add use_web_search to llm api keys

Revision ID: 8c5e6d6df0f5
Revises: e404a2bf6027
Create Date: 2026-07-30 05:40:55.689639
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '8c5e6d6df0f5'
down_revision: str | None = 'e404a2bf6027'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_api_keys', sa.Column('use_web_search', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_api_keys', 'use_web_search')
    # ### end Alembic commands ###
